[package]
name = "upscale_npu"
version = "0.1.0"
edition = "2021"

[dependencies]
ort =  { version = "2.0.0-rc.4", features = ["load-dynamic"] } 
ndarray = "0.16"
image = "0.25"
anyhow = "1.0"
rayon = "1.10"
tokenizers = "0.20"
reqwest = { version = "0.12", features = ["blocking"] }